# Generated by Django 2.0 on 2017-12-22 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiauth', '0003_auto_20171222_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrelation',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
